## 0_Imports e configs

In [1]:
import pandas as pd

## 1_Lendo dados dos estabelecimentos

In [2]:
df_business = pd.read_json('yelp_dataset/yelp_academic_dataset_business.json',lines=True,)
df_business = df_business[['business_id','name','city','state','stars','review_count','categories']]

##### Contando quantidade de estabelecimentos por estados

In [3]:
df_business.shape

(209393, 7)

In [4]:
business_per_state = df_business.groupby(by='state').count()['business_id'].sort_values(ascending=False)
state_list = business_per_state.index[0:10]
business_per_state

state
AZ     60803
NV     39084
ON     36627
OH     16392
NC     16218
PA     12376
QC     10233
AB      8682
WI      5525
IL      2034
SC      1328
CA        23
NY        22
TX         6
WA         5
AL         3
GA         3
FL         3
VT         2
NE         2
CT         2
MI         2
BC         2
UT         2
CO         2
AR         1
AK         1
YT         1
DOW        1
DUR        1
HI         1
HPL        1
MB         1
XWY        1
OR         1
VA         1
MO         1
Name: business_id, dtype: int64

##### Criando dicion√°rios para apendar as partes dos datasets dos estados

In [5]:
state_dict_parts = {}
state_business_list = {}
for state in state_list:
    state_dict_parts[state] = []
    state_business_list[state] = df_business.loc[df_business['state']== state,'business_id'].tolist()

## 2_Lendo dados das reviwes

In [12]:
df_reader = pd.read_json('yelp_dataset/yelp_academic_dataset_review.json',lines=True,chunksize=100000)

In [13]:
for state in state_list:
    print(f'{state}  ',end=', ')
print()
for part in df_reader:
    for state in state_list:
        part_x = part[part['business_id'].isin(state_business_list[state])]
        part_x = part_x[['business_id','stars','useful','funny','cool','text']]
        print(part_x.shape[0],end=', ')
        state_dict_parts[state].append(part_x)
    print()

AZ  , NV  , ON  , OH  , NC  , PA  , QC  , AB  , WI  , IL  ,
30514, 34079, 10996, 5136, 6652, 4920, 3002, 1534, 2036, 855,
30638, 34355, 10912, 5017, 6526, 4978, 2976, 1485, 1995, 840,
30311, 34513, 10737, 5118, 6573, 5016, 3032, 1536, 2022, 871,
30437, 34482, 11003, 4939, 6369, 4950, 3056, 1502, 2124, 848,
30313, 34934, 10929, 5002, 6416, 4862, 2852, 1556, 2050, 812,
30641, 35109, 10754, 5149, 6385, 4786, 2507, 1537, 2005, 787,
32203, 35829, 9111, 5104, 6632, 4682, 2472, 1312, 1631, 590,
32129, 35714, 9591, 4817, 6780, 4641, 2422, 1318, 1606, 519,
29956, 34962, 11708, 4619, 6895, 4644, 2795, 1569, 1946, 522,
30238, 34991, 11679, 4438, 6871, 4595, 2707, 1607, 1966, 559,
30178, 35224, 11550, 4601, 6857, 4631, 2634, 1555, 1962, 476,
30253, 35063, 11556, 4570, 6832, 4559, 2692, 1562, 2010, 514,
30424, 35347, 11496, 4572, 6972, 4514, 2404, 1531, 1863, 503,
30655, 35145, 11390, 4924, 6938, 4552, 2210, 1557, 1771, 481,
31468, 36176, 10144, 4890, 7370, 4311, 2020, 1168, 1543, 433,
32004, 35074, 10337, 5107, 7076, 4495, 2261, 1235, 1479, 470,
31884, 32865, 12416, 4749, 5996, 4964, 2947, 1530, 1704, 574,
31788, 33188, 12392, 4743, 5874, 4868, 2978, 1499, 1750, 604,
32067, 32672, 12377, 4801, 5925, 4915, 3007, 1521, 1801, 561,
31604, 33069, 12564, 4715, 5881, 4824, 2978, 1601, 1772, 590,
31669, 33270, 12538, 4932, 5868, 4820, 2729, 1533, 1696, 564,
32949, 32746, 11541, 5215, 6093, 5154, 2388, 1465, 1541, 476,
33572, 32901, 11049, 5267, 6308, 4796, 2507, 1247, 1426, 501,
32841, 34262, 10370, 5318, 6271, 4572, 2702, 1148, 1573, 569,
29179, 36627, 11485, 5337, 5875, 4370, 3012, 1198, 1974, 736,
28999, 36936, 11275, 5499, 5880, 4286, 3014, 1156, 2018, 717,
29249, 36647, 11220, 5468, 5994, 4435, 3013, 1117, 1954, 682,
29239, 36592, 11560, 5333, 5802, 4401, 3048, 1197, 1993, 644,
29349, 36929, 11511, 5227, 5745, 4282, 2802, 1314, 1963, 658,
29392, 36824, 11432, 5348, 5867, 4359, 2698, 1305, 1874, 638,
31523, 36740, 9789, 5493, 6228, 4457, 2222, 1046, 1619, 479,
31595, 36655, 9753, 5394, 6489, 4391, 2274, 1014, 1551, 480,
32855, 33564, 11236, 5252, 5932, 4179, 2511, 1267, 2006, 656,
32270, 33453, 11876, 5045, 5614, 4167, 2734, 1337, 2157, 810,
32274, 33382, 11807, 5197, 5712, 4229, 2646, 1244, 2194, 791,
32538, 33240, 11801, 5092, 5617, 4254, 2717, 1312, 2152, 776,
32536, 33560, 11727, 5083, 5616, 4058, 2559, 1361, 2194, 795,
32786, 33461, 11664, 4923, 5584, 4193, 2487, 1423, 2177, 759,
33319, 34333, 10345, 5097, 6434, 4461, 2075, 1167, 1687, 542,
33537, 34283, 10248, 5103, 6606, 4487, 2048, 1054, 1556, 517,
30341, 36116, 11414, 4681, 6291, 4546, 2474, 1345, 1851, 559,
28601, 36720, 12036, 4478, 6501, 4526, 2655, 1504, 2017, 636,
28375, 37141, 12008, 4473, 6473, 4477, 2592, 1546, 1988, 615,
28765, 36809, 12064, 4449, 6353, 4412, 2774, 1511, 1965, 584,
28579, 36575, 12075, 4567, 6300, 4748, 2556, 1638, 2064, 598,
28788, 36017, 12210, 4669, 6554, 4838, 2418, 1627, 2013, 552,
30564, 35618, 10932, 4722, 6809, 4982, 2344, 1349, 1803, 469,
32131, 35584, 9815, 4600, 7203, 4858, 2237, 1115, 1522, 423,
30305, 35376, 12217, 4912, 6399, 3934, 2438, 1382, 1990, 486,
30120, 35338, 12740, 4793, 6275, 3533, 2556, 1496, 2091, 515,
30124, 35301, 12794, 4794, 6274, 3706, 2606, 1402, 1990, 498,
30391, 35293, 12759, 4808, 6161, 3533, 2596, 1314, 2088, 493,
30077, 35101, 12623, 4875, 6417, 3791, 2436, 1549, 2112, 481,
30009, 35014, 12822, 4840, 6482, 3852, 2356, 1549, 1996, 521,
31976, 35251, 10473, 5129, 7041, 4131, 1999, 1241, 1729, 415,
32664, 35486, 9665, 5138, 7238, 4009, 2019, 1099, 1658, 410,
31621, 35121, 11263, 4533, 6404, 4228, 2395, 1400, 2153, 589,
31318, 35614, 11294, 4351, 6297, 4197, 2523, 1420, 2103, 592,
31524, 35355, 11248, 4396, 6295, 4296, 2459, 1400, 2133, 606,
31246, 35321, 11387, 4494, 6315, 4217, 2501, 1407, 2218, 607,
31572, 35116, 11358, 4404, 6302, 4231, 2343, 1531, 2257, 598,
31842, 34414, 11447, 4621, 6461, 4405, 2279, 1495, 2160, 599,
33364, 34922, 9971, 4545, 6815, 4465, 2124, 1167, 1701, 495,
34018, 35275, 9230, 4530, 6919, 4422, 2105, 1047, 1585, 390,
31511, 33352, 12647, 4864, 6333, 4093, 2926, 1483, 1859, 619,
30546, 33083, 13577, 4760, 6393, 3904, 3296, 1564, 2023, 643,
30549, 33180, 13626, 4869, 6175, 3960, 3230, 1523, 2011, 652,
30128, 33207, 13654, 4964, 6317, 3943, 3277, 1578, 2020, 682,
30911, 32635, 13487, 4992, 6314, 4003, 3093, 1672, 1971, 649,
31157, 32375, 13587, 4894, 6259, 4104, 3103, 1702, 1923, 658,
33262, 33503, 10847, 5165, 6656, 4224, 2615, 1309, 1560, 447,
33910, 33457, 10270, 5119, 6791, 4351, 2453, 1196, 1623, 416,
31347, 35909, 10639, 4366, 6112, 4279, 2667, 1646, 2053, 601,
31229, 36690, 10652, 4176, 5963, 4066, 2629, 1596, 2039, 626,
31417, 36579, 10575, 4137, 5937, 4079, 2651, 1517, 2078, 660,
31133, 36340, 10816, 4157, 6078, 4224, 2615, 1509, 2137, 588,
31490, 36128, 10733, 4341, 5925, 4119, 2442, 1766, 2010, 678,
31511, 36009, 10906, 4204, 5960, 4148, 2457, 1720, 2100, 659,
33540, 34929, 9830, 4924, 6317, 4573, 2167, 1169, 1552, 495,
33570, 34897, 9843, 4897, 6358, 4440, 2196, 1262, 1498, 547,
7493, 7311, 1860, 1027, 1369, 900, 426, 211, 298, 97,

In [14]:
for state in state_list:
    df_reviews_x = pd.concat(state_dict_parts[state],axis=0)
    df_reviews_x.to_csv(f'yelp_dataset/reviews/{state}_reviews.csv')
    print(f'{state}: {df_reviews_x.shape[0]}')

AZ: 2870175
NV: 3216024
ON: 1041884
OH: 450195
NC: 587614
PA: 412145
QC: 243611
AB: 130837
WI: 176621
IL: 57792