In [1]:
import pandas as pd

In [2]:
# Importando base e retirando colunas desnecessárias 
business_json_path = 'data/yelp_academic_dataset_business.json'
data_business = pd.read_json(business_json_path, lines=True)
drop_columns = ['name', 'address', 'postal_code', 'latitude', 'longitude', 'review_count', 'attributes', 'hours']
data_business = data_business.drop(drop_columns, axis=1)

# Filtrando apenas business da Pensilvânia (PA)
final_business = data_business[data_business['state'] == 'PA']
final_business

,business_id,city,state,stars,is_open,categories
11,7Dv4_HAxsxvadEsT5fxQBg,Pittsburgh,PA,5.0,1,"Automotive, Auto Repair"
39,_4Oe9V-qTpU5iemM9bphlA,Pittsburgh,PA,3.5,1,"Oil Change Stations, Auto Repair, Automotive, ..."
63,ZkzutF0P_u0C0yTulwaHkA,Plum,PA,4.0,1,"Restaurants, Pizza"
69,UyZqOcWxShRRtACCkZFkpQ,Pittsburgh,PA,5.0,1,"Pet Sitting, Pets, Pet Stores, Pet Services, P..."
129,OGVHlFHSXjHuioOvm1wVqg,Avalon,PA,4.0,1,"Dive Bars, Restaurants, Comfort Food, Bars, Ni..."
...,...,...,...,...,...,...
209270,5DpltRkGtV8AnYOlIAt-qA,Pittsburgh,PA,5.0,1,"Shopping, Tobacco Shops"
209277,qWcaGio9JsqrvgmQiIRtIQ,Bridgeville,PA,4.0,1,"Food, Restaurants, Bakeries, Pizza, Sandwiches"
209291,qhmJE8vAy2PvZ-uZS7kifA,McMurray,PA,2.5,1,"Smog Check Stations, Oil Change Stations, Auto..."
209301,NeM7anGnTOTn7sEJavS3sw,Bridgeville,PA,4.5,1,"Food, Coffee & Tea"
209344,kPwYdRKp1-W1-tUR8iylxw,Ross Township,PA,4.0,1,"Juice Bars & Smoothies, Mediterranean, Restaur..."

In [ ]:
size = 1000000
review_json_path = 'data/yelp_academic_dataset_review.json'
review = pd.read_json(review_json_path, lines=True, chunksize=size)

# Merge da base de dados de review com a base de dados de business já filtrada
chunk_list = []
for chunk_review in review:
    chunk_review = chunk_review.drop(['review_id', 'user_id','useful','funny','cool'], axis=1).rename(columns={'stars': 'review_stars'})
    chunk_merged = pd.merge(final_business, chunk_review, on='business_id', how='inner')
    print(f"{chunk_merged.shape[0]} out of {size:,} related reviews")
    chunk_list.append(chunk_merged)
    
final_df = pd.concat(chunk_list, ignore_index=True, join='outer', axis=0)
print(final_df)

# Gerando CSV de novo dataset
final_csv_name = "yelp_reviews_PA.csv"
final_df.to_csv(final_csv_name, index=False)